# Generated by Django 3.2.16 on 2022-11-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='discover',
            name='disease_code',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='diseaseTypeId',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publicservant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='record',
            name='disease_code',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='specialize',
            name='diseaseTypeId',
        ),
        migrations.RemoveField(
            model_name='specialize',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='cname',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Discover',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='DiseaseType',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='PublicServant',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Specialize',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
